;******************************************************************************
;* C H A R G E N G * U T I L S 0 0 2 a * T h o m a s   H o l t e * 8 6 0 1 1 9*
;******************************************************************************
;*									      *
;*    L A N G U A G E   D E P E N D E N T   P A R T   O F   C H A R G E N     *
;*    ===================================================================     *
;*									      *
;*  		        ( G E R M A N   V E R S I O N )		      	      *
;*		        ===============================         	      *
;*									      *
;*									      *
;*  Version 1.0						        Thomas Holte  *
;*									      *
;******************************************************************************

	.Z80	
	GLOBAL ENDMSG,ERROR1,ERROR2,EXIT,MENU,NATIONAL,STORE

;ASCII control code:
LF	EQU  0AH		;line feed
ESC	EQU  1BH		;escape

MENU:	DEFM '*** CP/M 3 ***  TT.MM.JJ  HH:MM:SS    Zeichengenerator    '
	DEFB 98H
	DEFM ' 1985 by Thomas Holte'
	DEFM '                                        '
	DEFM '                                        '
	DEFM 'Code --> '
	DEFW 7F7FH
	DEFM '  Zeichen ----> '
	DEFB 80H
	DEFM '  Zeichensatz ---->                                 '
	DEFM '                                        '
 	DEFM '                                        '
	DEFM '                                0 1 2 3 '
	DEFM '4 5 6 7                                 '
	DEFM '                              0         '
	DEFM '       0                                '
	DEFM '                              1         '
	DEFM '       1                                '
	DEFM '                              2         '
	DEFM '       2                                '
	DEFM '                              3         '
	DEFM '       3                                '
	DEFM '                              4         '
	DEFM '       4                                '
	DEFM '                              5         '
	DEFM '       5                                '
	DEFM '                              6         '
	DEFM '       6                                '
	DEFM '                              7         '
	DEFM '       7                                '
	DEFM '                              8         '
	DEFM '       8                                '
	DEFM '                              9         '
	DEFM '       9                                '
	DEFM '                             10         '
	DEFM '       10                               '
	DEFM '                             11         '
	DEFM '       11                               '
	DEFM '                             12         '
	DEFM '       12                               '
	DEFM '                             13         '
	DEFM '       13                               '
	DEFM '                             14         '
	DEFM '       14                               '
	DEFM '                             15         '
	DEFM '       15                               '
	DEFM '                                0 1 2 3 '
	DEFM '4 5 6 7                                 '
	DEFM '                                        '
	DEFM '                                        '
	DEFM 'P4/P5=vor/zur}ck    N/S=Nicht/Speichern '
	DEFM '  P1=Editieren   BREAK=Abbruch  ESC=Quit'

	DEFM 'Deutsch '
	DEFM 'ASCII   '
	DEFM 'Graphik '

ENDMSG:	DEFM 'Dr}cken Sie <RESET>, um den neu definierten Zeichensatz zu laden'
	DEFB LF,0

EXIT:	DEFB 'N'
STORE:	DEFB 'S'

ERROR1:	DEFB LF
	DEFM 'Fataler E/A-Fehler'
	DEFB LF,0
ERROR2:	DEFB LF
	DEFM 'Diskette schreibgesch}tzt'
	DEFB LF,0

NATIONAL:
	DEFB ESC,'G',0

	END
