;******************************************************************************
;*  C O P Y G  *  U T I L S 0 0 4 a  *  T h o m a s   H o l t e * 8 5 0 9 2 3 *
;******************************************************************************
;*									      *
;*  	  L A N G U A G E   D E P E N D E N T   P A R T   O F   C O P Y       *
;*        =============================================================       *
;*									      *
;*  			 ( G E R M A N   V E R S I O N )		      *
;*			 =============================== 		      *
;*									      *
;*  Version 1.0							Thomas Holte  *
;*									      *
;******************************************************************************

	.Z80

	GLOBAL ALL,BOOT,CANCEL,END,ERROR2,ERROR3,ERROR4,ERROR5,ERROR6,ERROR7
	GLOBAL FILES,NATIONAL,PRMPT1,PRMPT2,PRMPT3,PRMPT4,PRMPT5,PRMPT6,PRMPT7
	GLOBAL PRMPT8,PRMPT9,PRMT10,PRMT11,PRMT12,PRMT13,PRMT14,PROCEED,RETRY
	GLOBAL YES

;ASCII control code:
LF	EQU  0AH		;line feed	
ESC	EQU  1BH		;escape

NATIONAL:
	DEFB ESC,'G',0

ERROR2: DEFB LF
	DEFM 'Ung}ltiges Quellaufwerk'
	DEFB LF,0
ERROR3: DEFB LF
	DEFM 'Ung}ltiges Ziellaufwerk'
	DEFB LF,0
ERROR4: DEFB LF
	DEFM 'Unterschiedliche Laufwerksspezifikationen'
	DEFB LF,0
ERROR5: DEFB LF
	DEFM 'Nicht gen}gend Speicherplatz verf}gbar'
	DEFB LF,0
ERROR6:	DEFB LF,LF
	DEFM 'Fataler E/A-Fehler'
	DEFB LF,0
ERROR7:	DEFB LF,LF
	DEFM 'Diskette schreibgesch}tzt'
	DEFB LF,0

PRMPT1: DEFB LF
	DEFM 'Kopier Ver 3.3'
	DEFB LF,0
PRMPT2: DEFB LF
	DEFM 'Modus    Funktion'
	DEFB LF,LF
	DEFM 'ALLES    Kopieren der ganzen Diskette'
	DEFB LF
	DEFM 'SYSTEM   Kopieren der Systemspuren'
	DEFB LF
	DEFM 'DATEN    Kopieren der Datenspuren'
	DEFB LF
	DEFM 'ENDE     Programmende'
	DEFB LF,LF
	DEFM 'Modus: '
	DEFB 0
PRMPT3: DEFB LF
	DEFM 'Quellaufwerk: '
	DEFB 0
PRMPT4: DEFB LF
	DEFM 'Ziellaufwerk: '
	DEFB 0
PRMPT5: DEFB LF
	DEFM '(^C f}r Programmabbruch)'
	DEFB LF
	DEFM 'Dr}cken Sie <ENTER>, um '
	DEFB 0
PRMPT6: DEFM ' von '
	DEFB 0
PRMPT7: DEFM ' nach '
	DEFB 0
PRMPT8: DEFM ' zu kopieren '
	DEFB 0
PRMPT9:	DEFB LF,LF
	DEFM 'Dr}cken Sie <ENTER>, wenn Quelldiskette in Laufwerk '
	DEFB 0
PRMT10:	DEFB LF,LF
	DEFM 'Dr}cken Sie <ENTER>, wenn Zieldiskette in Laufwerk '
	DEFB 0
PRMT11:	DEFM 'Lesen     von Spur    '
	DEFB 0
PRMT12:	DEFM 'Schreiben von Spur    '
	DEFB 0
PRMT13:	DEFB LF,LF
	DEFM 'M|chten Sie das Kopieren wiederholen ? '
	DEFB 0
PRMT14:	DEFB LF
	DEFM '(A)bbrechen, (F)ortfahren oder (W)iederholen'
	DEFB LF,0
 
ALL:	DEFM 'ALLES'
	DEFB 0
BOOT:	DEFM 'SYSTEM'
	DEFB 0
FILES:	DEFM 'DATEN'
	DEFB 0
END:	DEFM 'ENDE'
	DEFB 0

CANCEL:	DEFB 'A'
PROCEED:DEFB 'F'
RETRY:	DEFB 'W'
YES:	DEFB 'J'

	END
