;******************************************************************************
;*  F O R M A T G * U T I L S 0 0 6 a * T h o m a s   H o l t e * 8 5 0 6 0 9 *
;******************************************************************************
;*									      *
;*     L A N G U A G E   D E P E N D E N T   P A R T   O F   F O R M A T      *
;*     =================================================================      *
;*									      *
;*  		       ( G E R M A N   V E R S I O N )			      *
;*		       =============================== 			      *
;*									      *
;*									      *
;*  Thomas Holte						 Version 1.0  *
;*									      *
;******************************************************************************

	.Z80

	GLOBAL CANCEL,ERROR1,ERROR2,ERROR3,ERROR4,ERROR5,ERROR6,ERROR7,ERROR8
	GLOBAL ERROR9,ERR10,ERR11,NATIONAL,PRMPT1,PRMPT2,PRMPT3,PRMPT4,PRMPT5
	GLOBAL PRMPT6,PRMPT7,PRMPT8,PRMPT9,PRMT10,PROCEED,RETRY,YES

;ASCII control codes:
BS	EQU  08H		;backspace
LF	EQU  0AH		;line feed
VT	EQU  0BH		;vertical tabulation 
CR	EQU  0DH		;carriage return
ESC	EQU  1BH		;escape

PRMPT1:	DEFM 'M|chten Sie wirklich den Datentr{ger in Laufwerk '
	DEFB 0
PRMPT2: DEFM ' formatieren ? '
	DEFB 0
PRMPT3:	DEFB LF
	DEFM 'Formatieren von Spur   '
	DEFB 0
PRMPT4:	DEFM 'Verifizieren von Spur   '
	DEFB 0
PRMPT5:	DEFB LF
	DEFM 'Formatieren von Spur    '
	DEFB 0
PRMPT6:	DEFB CR
	DEFM 'Verifizieren von Spur    '
	DEFB BS,0
PRMPT7:	DEFM ' defekte Bl|cke'
	DEFB 0
PRMPT8:	DEFB CR,VT
	DEFM 'Verifizieren von Spur '
	DEFB 0
PRMPT9:	DEFB LF,LF
	DEFM 'Initialisieren des Inhaltsverzeichnisses'
	DEFB LF
	DEFB 0
PRMT10:	DEFB LF
	DEFM '(A)bbrechen, (F)ortfahren, or (W)iederholen'
	DEFB LF,0

ERROR1:	DEFM 'Ung}ltiger Laufwerksname (Benutzen Sie '
	DEFB 0
ERROR2:	DEFB LF,LF
	DEFM 'Ung}ltiges Laufwerk'
	DEFB LF,0
ERROR3:	DEFB LF,LF
	DEFM 'Ung}ltige Spur'
	DEFB LF,0
ERROR4:	DEFB LF,LF
	DEFM 'Ung}ltiger Sektor'
	DEFB LF,0
ERROR5:	DEFB LF,LF
	DEFM 'Laufwerk nicht bereit'
	DEFB LF,0
ERROR6:	DEFB LF,LF
	DEFM 'Diskette schreibgesch}tzt'
	DEFB LF,0
ERROR7:	DEFB LF,LF
	DEFM 'Laufwerksfehler'
	DEFB LF,0
ERROR8:	DEFB LF,LF
	DEFM 'Datenrecord nicht gefunden'
	DEFB LF,0
ERROR9:	DEFB LF,LF
	DEFM 'CRC-Fehler'
	DEFB LF,0
ERR10:	DEFB LF,LF
	DEFM 'Daten verloren'
	DEFB LF,0
ERR11:	DEFB LF,LF
	DEFM 'FESTPLATTENLAUFWERK DEFEKT'
	DEFB LF,0 

NATIONAL:
	DEFB ESC,'G',0

CANCEL:	DEFB 'A'
PROCEED:DEFB 'F'
RETRY:	DEFB 'W'
YES:	DEFB 'J'	

	END
		