;******************************************************************************
;*  B A C K U P G * U T I L S 0 0 1 a * T h o m a s   H o l t e * 8 5 0 2 0 7 *
;******************************************************************************
;*									      *
;*  	L A N G U A G E   D E P E N D E N T   P A R T   O F   B A C K U P     *
;*      =================================================================     *
;*									      *
;*  			 ( G E R M A N   V E R S I O N )		      *
;*			 =============================== 		      *
;*									      *
;*  Version 1.0							Thomas Holte  *
;*									      *
;******************************************************************************

	.Z80

	GLOBAL CANCEL,ERROR2,ERROR3,ERROR4,ERROR5,ERROR6,ERROR7,NATIONAL,PRMPT1
	GLOBAL PRMPT2,PRMPT3,PRMPT4,PRMPT5,PRMPT6,PRMPT7,PRMPT8,PRMPT9,PRMT10
	GLOBAL PRMT11,PRMT12,PRMT13,PRMT14,PRMT15,PROCEED,RESTORE,RETRY,SAVE

;ASCII control code:
BEL	EQU  07H		;bell
BS	EQU  08H		;backspace
LF	EQU  0AH		;line feed	
ESC	EQU  1BH		;escape

NATIONAL:
	DEFB ESC,'G',0

ERROR2: DEFB LF
	DEFM 'Ung}ltiges Quellaufwerk'
	DEFB 0
ERROR3: DEFB LF
	DEFM 'Ung}ltiges Ziellaufwerk'
	DEFB 0
ERROR4: DEFB LF
	DEFM 'Nicht gen}gend Speicherplatz verf}gbar'
	DEFB 0
ERROR5:	DEFB LF,LF
	DEFM 'Fataler E/A-Fehler'
	DEFB LF,0
ERROR6:	DEFB LF,LF
	DEFM 'Datentr{ger schreibgesch}tzt'
	DEFB LF,0
ERROR7:	DEFB LF
	DEFM '*** ACHTUNG *** FALSCHER DATENTR[GER ***'
	DEFB 0

PRMPT1: DEFB LF
	DEFM 'Backup Ver. 4.0'
	DEFB LF,0
PRMPT2: DEFB LF
	DEFM 'Modus  Funktion'
	DEFB LF,LF
	DEFM 'S      Sichern eines Datentr{gers'
	DEFB LF
	DEFM 'R      Restaurieren eines Datentr{gers'
	DEFB LF,LF
	DEFM 'Modus: '
	DEFB 0
PRMPT3: DEFB LF
	DEFM 'Quellaufwerk: '
	DEFB 0
PRMPT4: DEFB LF
	DEFM 'Ziellaufwerk: '
	DEFB 0
PRMPT5: DEFB LF
	DEFM '(^C f}r Programmabbruch)'
	DEFB LF,0
PRMPT6:	DEFM 'Dr}cken Sie <ENTER>, um Datentr{ger '
	DEFB 0
PRMPT7: DEFB ' zu sichern ',0
PRMPT8: DEFM 'Dr}cken Sie <ENTER>, um Datentr{ger '
	DEFB 0
PRMPT9: DEFB ' zu restaurieren ',0
PRMT10:	DEFB LF,LF,BEL
	DEFM 'Legen Sie den n{chsten Datentr{ger in Laufwerk '
	DEFB 0
PRMT11:	DEFM ' ein und dr}cken Sie <ENTER> '
	DEFB 0
PRMT12:	DEFM 'Lesen von Block            '
	DEFB BS,BS,BS,BS,BS,BS,BS,0
PRMT13:	DEFM 'Schreiben von Block        '
	DEFB BS,BS,BS,0
PRMT14:	DEFM 'Verifizieren von Block     '
	DEFB 0
PRMT15:	DEFB LF
	DEFM '(A)bbrechen, (F)ortfahren oder (W)iederholen'
	DEFB LF,0
 
SAVE:	DEFB 'S',0
RESTORE:DEFB 'R',0

CANCEL:	DEFB 'A'
PROCEED:DEFB 'F'
RETRY:	DEFB 'W'

	END
