;******************************************************************************
;*  F K E Y E  *  U T I L S 0 0 5 a  *  T h o m a s   H o l t e * 8 6 0 1 1 9 *
;******************************************************************************
;*                                                                            *
;*  	 L A N G U A G E   D E P E N D E N T   P A R T   O F   F K E Y	      *
;*       =============================================================        *
;*									      *
;*  			( E N G L I S H   V E R S I O N )		      *
;*			=================================		      *
;*                                                                            *
;*                                                                            *
;*  Version 1.0                                                 Thomas Holte  *
;*                                                                            *
;******************************************************************************

        .Z80

        GLOBAL ENDMSG,ERROR1,ERROR2,MENU,NATIONAL,NO,YES

;ASCII control codes:
LF	EQU  0AH		;line feed
ESC	EQU  1BH		;escape

MENU:	DEFM '*** CP/M 3 ***  MM/DD/YY  HH:MM:SS   Fun'
	DEFM 'ction Key Programmer   '
	DEFB 98H
	DEFM ' 1985 by T.Holte'
	DEFM '                                        '
	DEFM '                                        '
	DEFM 'This utility allows you to program the f'
	DEFM 'unction keys F1 - F8 and P1 - P5 with up'
	DEFM 'to 73 characters.                       '
	DEFM '                                        '
	DEFM 'Enter  spaces  with  the  underline  cha'
	DEFM 'racter  "_"  and  control  codes  with a'
	DEFM 'circumflex and the appropriate letter, e'
	DEFM '.g. "^C" for CONTROL-C.                 '
	DEFM '                                        '
	DEFM '                                        '
	DEFM '                                        '
	DEFM '                                        '
	DEFM 'F1 -->                                  '
	DEFM '                                        '
	DEFM 'F2 -->                                  '
	DEFM '                                        '
	DEFM 'F3 -->                                  '
	DEFM '                                        '
	DEFM 'F4 -->                                  '
	DEFM '                                        '
	DEFM 'F5 -->                                  '
	DEFM '                                        '
	DEFM 'F6 -->                                  '
	DEFM '                                        '
	DEFM 'F7 -->                                  '
	DEFM '                                        '
	DEFM 'F8 -->                                  '
	DEFM '                                        '
	DEFM 'P1 -->                                  '
	DEFM '                                        '
	DEFM 'P2 -->                                  '
	DEFM '                                        '
	DEFM 'P3 -->                                  '
	DEFM '                                        '
	DEFM 'P4 -->                                  '
	DEFM '                                        '
	DEFM 'P5 -->                                  '
	DEFM '                                        '
	DEFM '                                        '
	DEFM '                                        '
	DEFM '                                        '
	DEFM '                                        '
	DEFM 'Are all entries correct (Y/N) --> '
	DEFB 7FH
	DEFM '     '
	DEFM '                                        '

ERROR1:	DEFB LF
	DEFM 'Fatal I/O error'
	DEFB LF,0
ERROR2:	DEFB LF
	DEFM 'Diskette write protected'
	DEFB LF,0 

NATIONAL:
	DEFB ESC,'A',0

ENDMSG:	DEFM 'Press <RESET> to activate programmed function keys'
	DEFB LF,0

NO:	DEFB 'N'
YES:	DEFB 'Y'

	END
