;******************************************************************************
;*  M 6 8 4 5 E  *  U T I L S 0 0 7 a * T h o m a s   H o l t e * 8 6 0 1 1 9 *
;******************************************************************************
;*                                                                            *
;*  	 L A N G U A G E   D E P E N D E N T   P A R T   O F   M 6 8 4 5      *
;*       ===============================================================      *
;*									      *
;*			 ( E N G L I S H   V E R S I O N )		      *
;*			 =================================		      *
;*									      *
;*                                                                            *
;*  Thomas Holte                                                 Version 1.0  *
;*                                                                            *
;******************************************************************************

	.Z80

	GLOBAL ERROR1,ERROR2,MENU,NATIONAL

;ASCII control codes:
LF	EQU  0AH		;line feed	
ESC	EQU  1BH		;escape

MENU:	DEFB 8AH
	REPT 19
	DEFB 81H,81H,81H,86H
	ENDM
	DEFB 81H,81H,89H
	REPT 9 
	REPT 19
	DEFB 80H
	DEFM '   '
	ENDM
	DEFB 80H
	DEFW '  '
	DEFB 80H,84H
	REPT 19
	DEFB 81H,81H,81H,82H
	ENDM
	DEFB 81H,81H,83H
	ENDM
	REPT 19
	DEFB 80H
	DEFM '   '
	ENDM
	DEFB 80H
	DEFW '  '
	DEFB 80H
	DEFB 84H,81H,81H,81H
	REPT 12
	DEFB 85H,81H,81H,81H
	ENDM
	DEFB 82H,81H,81H,81H
	REPT 5 
	DEFB 85H,81H,81H,81H
	ENDM
	DEFB 85H,81H,81H,83H	
	DEFB 80H
	DEFM '                                           -->     '
	DEFB 80H
	DEFM '  M6845 adjustment tool   '
	DEFB 80H,84H
	REPT 51
	DEFB 81H
	ENDM
	DEFB 85H
	REPT 26
	DEFB 81H
	ENDM
	DEFB 83H,80H,' ',8FH
	DEFM ' = val--  '
	DEFB 90H
	DEFM ' = val++  P4 = prev par  P'
	DEFM '5 = next par  BREAK = abort ESC = quit '
	DEFB 80H
	DEFB 88H
	REPT 78
	DEFB 81H
	ENDM
	DEFB 87H,0
	DEFM 'Horizontal Total          Register (R0) '
	DEFM 'Horizontal Displayed      Register (R1) '
	DEFM 'Horizontal Sync Position  Register (R2) '
	DEFM 'Horizontal Sync Width     Register (R3) '
	DEFM 'Vertical   Total          Register (R4) '
	DEFM 'Vertical   Total Adjust   Register (R5) '
	DEFM 'Vertical   Displayed      Register (R6) '
	DEFM 'Vertical   Sync Position  Register (R7) '
	DEFM 'Interlace  Mode           Register (R8) '
	DEFM 'Maximum Scan Line Address Register (R9) '
	DEFM 'Cursor Start              Register (R10)'
	DEFM 'Cursor End                Register (R11)'

	DEFS 12*3

ERROR1:	DEFB LF
	DEFM 'Fatal I/O error'
	DEFB LF,0
ERROR2:	DEFB LF
	DEFM 'Diskette write protected'
	DEFB LF,0

NATIONAL:
	DEFB ESC,'A',0

	END
