 nicht erlaubt
 darf nicht sein
 Konstante
 tut nicht
 Ausdruck
 Bezeichner
 file
 hier
 Integer
 File
 verbotene
 oder
 undefiniert
 passen zu
 real
 String
 Textfile
 ausserhalb des Bereichs
 Variable
 Ueberlauf
 wird erwartet
 typ
 ungueltig
 pointer
01';'
02':'
03','
04'('
05')'
06'='
07':='
08'['
09']'
10'.'
11'..'
12BEGIN
13DO
14END
15OF
17THEN
18TO DOWNTO
20Boolean
21
22
23
24
25
26
27
28Pointer
29Record
30einfacher
31einfacher
32
33
34
35
36Typen
37Untyped
40er label
41unbekannte(r) Schreibfehler
42er in vorhergehenderen Definition
43Mehrfache label:Name wurde bereits in diesem Block verwendet !
44Typen stimmen nicht ueberein
45
46 und CASE selector stimmen nicht ueberein
47Operand passt nicht zum operator
48er Ergebnis
49e  laenge
50n laenge passt nicht zum
51er Unterbereichsbasis
52 Untere Grenze > Obere Grenze
53Reserviertes Wort
54 Zuweisung
55 ueberschreitet Zeile
56Fehler in der integern
57Fehler in dern
58s Zeichen im
60n sind
61s und sind
62Strukturierten sind
63ssind
64s und untypeds sind
65Untypeds sind
66Ein-/Ausgabe
67s mueenn parameter sein
68bestandteile d}rfen keines sein
69 Anforderung von Feldern
70Mengenbasis
71es GOTO
72Marke liegt nicht im gueltigen Block
73e FORWARD procedure(s)
74INLINE fehler
75r Gebrauch von ABSOLUTE
90 nicht gefunden
91Unerwartetes Ende der Quelldatei
92Overlays koennen nicht benutzt werden
93e Compiler Options
96Geschachtelte Include  sind
97Zu viele geschachtelte WITH's
98Speicher
99Compiler