;******************************************************************************
;*  I N I T W E  *  C P M S Y S 5 b  *  T h o m a s   H o l t e * 8 5 1 1 3 0 *
;******************************************************************************
;*									      *
;*  	 L A N G U A G E   D E P E N D E N T   P A R T   O F   I N I T W      *
;*       ===============================================================      *
;*									      *
;*  			( E N G L I S H   V E R S I O N )		      *
;*			=================================		      *
;*									      *
;*  Version 1.1							Thomas Holte  *
;*									      *
;******************************************************************************

	.Z80

	GLOBAL CANCEL,DRIVE,ERROR1,ERROR2,ERROR3,ERROR4,ERROR5,ERROR6,ERROR7
	GLOBAL NATIONAL,PRMPT1,PRMPT2,PRMPT3,PRMT31,PRMPT4,PRMPT5,PRMPT6,PRMPT7
	GLOBAL PRMPT8,PROCEED,TYPE0,TYPE1,TYPE2,TYPE3

;ASCII control code:
BS	EQU  08H		;backspace
LF	EQU  0AH		;line feed	
VT	EQU  0BH		;vertical tabulation
CR	EQU  0DH		;carriage return
ESC	EQU  1BH		;escape

PRMPT1:	DEFB LF
	DEFM 'Initialization of a CP/M Ver 3 Hard Disk System'
	DEFB LF,LF
	DEFM 'Configuration table:'
	DEFB LF,0
PRMPT2:	DEFB LF
	DEFM 'Disk already initialized'
	DEFB LF
	DEFM 'Reply (C)ancel or (P)roceed'
	DEFM LF,0
PRMPT3:	DEFB LF
	DEFM 'Formatting'
	DEFB 0
PRMT31:	DEFM ' track     '
	DEFB 0
PRMPT4:	DEFB CR
	DEFM 'Verifying track      '
	DEFB BS,0
PRMPT5:	DEFM ' bad sectors detected'
	DEFB 0
PRMPT6:	DEFB CR,VT
	DEFM 'Verifying track '
	DEFB 0
PRMPT7:	DEFB LF,LF
	DEFM 'Initializing directory'
	DEFB LF,0
PRMPT8:	DEFB LF
	DEFM 'Copying system'
	DEFB LF,0

ERROR1:	DEFB LF
	DEFM 'Can''t open CPM3HD.SYS'
	DEFB LF,0
ERROR2:	DEFB LF
	DEFM 'Out of memory'
	DEFB LF,0
ERROR3:	DEFB LF
	DEFM 'Synchronization error'
	DEFB LF,0
ERROR4:	DEFB LF
	DEFM 'Can''t create C:CPM3.SYS'
	DEFB LF,0
ERROR5:	DEFB LF
	DEFM 'Can''t open CCP.COM'
	DEFB LF,0
ERROR6:	DEFB LF
	DEFM 'Can''t create C:CCP.COM'
	DEFB LF,0
ERROR7:	DEFB LF
	DEFM 'WINCHESTER DISK DRIVE FAULT'
	DEFB LF,0

CANCEL:	DEFB 'C'
PROCEED:DEFB 'P'

NATIONAL:
	DEFB ESC,'A',0

DRIVE:	DEFM 'Drive'
	DEFB 0

TYPE0:	DEFM 'Winchester'
	DEFB 0
TYPE1:	DEFM 'Winchester (cartridge)'
	DEFB 0
TYPE2:	DEFM 'mini floppy'
	DEFB 0
TYPE3:	DEFM 'standard floppy'
	DEFB 0 

	END
