. Note: Use TRSDOS 6.2.1 to get old-style dates and
. thus avoid password problems with other DOSes.
format :#d#(sden,sides=1,cyl=80,dir=17,name="xtrsutil",q=n,abs)
import -l export.cmd export/cmd:#D#
import -ln export.z80 export/z80:#D#
import -l import.cmd import/cmd:#D#
import -ln import.z80 import/z80:#D#
import -ln settime.z80 settime/z80:#D#
import -l settime.cmd settime/cmd:#D#
import -ln xtrsemt.ccc xtrsemt/ccc:#D#
import -ln xtrsemt.h xtrsemt/h:#D#
import -ln settime.ccc settime/ccc:#D#
import -ln m1format.fix m1format/fix:#D#
import -l xtrshard.dct xtrshard/dct:#D#
import -ln xtrshard.z80 xtrshard/z80:#D#
import -l xtrs8.dct xtrs8/dct:#D#
import -ln xtrs8.z80 xtrs8/z80:#D#
import -l xtrsmous.cmd xtrsmous/cmd:#D#
import -ln xtrsmous.z80 xtrsmous/z80:#D#
import -ln cd.ccc cd/ccc:#D#
import -ln pwd.ccc pwd/ccc:#D#
import -ln unix.ccc unix/ccc:#D#
import -ln mount.ccc mount/ccc:#D#
import -ln truedam.ccc truedam/ccc:#D#
import -ln umount.ccc umount/ccc:#D#
import -l cd.cmd cd/cmd:#D#
import -l pwd.cmd pwd/cmd:#D#
import -l unix.cmd unix/cmd:#D#
import -l mount.cmd mount/cmd:#D#
import -l umount.cmd umount/cmd:#D#
import -l truedam.cmd truedam/cmd:#D#
import -l cd6.cmd cd6/cmd:#D#
import -l pwd6.cmd pwd6/cmd:#D#
import -l unix6.cmd unix6/cmd:#D#
import -l mount6.cmd mount6/cmd:#D#
import -l umount6.cmd umount6/cmd:#D#
import -l truedam6.cmd truedam6/cmd:#D#
import -ln expall.bas expall/bas:#D#
import -ln do6.jcl do6/jcl:#D#
