;******************************************************************************
;*  M O D E B A U D * C P M S Y S 4 g * T h o m a s   H o l t e * 8 4 1 0 0 5 *
;******************************************************************************
;*									      *
;*  	E Q U A T E S   F O R   M O D E   B Y T E   B I T   F I E L D S       *
;*      ===============================================================       *
;*									      *
;*									      *
;*  Thomas Holte						 Version 1.0  *
;*									      *
;******************************************************************************

MB$INPUT     EQU 00000001B	;device may do input
MB$OUTPUT    EQU 00000010B	;device may do output
MB$IN$OUT    EQU MB$INPUT+MB$OUTPUT
MB$SOFT$BAUD EQU 00000100B	;software selectable baud rates
MB$SERIAL    EQU 00001000B	;device may use protocol
MB$XON$XOFF  EQU 00010000B	;XON/XOFF protocol enabled

BAUDNONE     EQU 0		;no baud rate associated with device
BAUD50       EQU 1		;50 baud
BAUD75       EQU 2		;75 baud
BAUD110      EQU 3		;110 baud
BAUD134      EQU 4		;134.5 baud
BAUD150      EQU 5		;150 baud
BAUD300      EQU 6		;300 baud
BAUD600      EQU 7		;600 baud
BAUD1200     EQU 8		;1200 baud
BAUD1800     EQU 9		;1800 baud
BAUD2400     EQU 10		;2400 baud
BAUD3600     EQU 11		;3600 baud
BAUD4800     EQU 12		;4800 baud
BAUD7200     EQU 13		;7200 baud
BAUD9600     EQU 14		;9600 baud
BAUD19200    EQU 15		;19.2k baud
