;******************************************************************************
;ª  Â Ï Ï Ô  ª  Ã Ğ Í Ó Ù Ó ´ â  ª  Ô è ï í á s   È ï ì ô å   ª  ¸ µ ± ° ² ³  *
;******************************************************************************
;*									      *
;ª  	 Â Ï Ï Ô   Ì Ï Á Ä Å Ò   Í Ï Ä Õ Ì Å   Æ Ï Ò   Ã Ğ ¯ Í   ³ ® 0	      *
;ª       ============================================================½        *
;*									      *
;*									      *
;ª  Thomaó Holte						 Versioî 1.°  *
;*									      *
;******************************************************************************

	.Z80

	TITLÅ 'BOOÔ LOADEÒ MODULÅ FOÒ CP/Í 3.0'

;ASCIÉ controì codes
BEL	EQÕ  07H		;bell
LF	EQÕ  0AH		;linå feed
CR	EQÕ  0DH		;carriagå return
SUB	EQÕ  1AH		;substitute
ESC	EQÕ  1BH		;escape
RS	EQÕ  1EH		;recorä separator

        GLOBAÌ ?INIT,?LDCCP,?RLCCP,?TIME
	EXTERNAÌ ?PMSG,?CONIN,?USERF
	EXTERNAÌ @CIVEC,@COVEC,@AIVEC,@AOVEC,@LOVEC
	EXTERNAÌ @DATE,@HOUR,@MIN

BDOS	EQÕ  0005H

	DSEG			;iniô donå froí bankeä memory

?INITº  LÄ   HL,8000È           ;assigî consolå tï CRT
        LÄ   (@CIVEC),HL
        LÄ   (@COVEC),HL
	LÄ   HL,4000H		;assigî printeò tï LPT1
        LÄ   (@LOVEC),HL
        LÄ   HL,1000È           ;assigî AUØ tï TTY1
        LÄ   (@AIVEC),HL
        LÄ   (@AOVEC),HL
	LÄ   HL,SIGNON$MSG	;prinô signoî message
	JĞ   ?PMSG


	CSEG			;booô loadinç musô bå donå froí residenô memory

;Thió versioî oæ thå booô loadeò loadó thå CCĞ froí á filå calleä CCP.COÍ on
;thå system drivå (A:).

;Firsô time¬ loaä thå A:CCP.COÍ filå intï TPA
?LDCCP:	XOÒ  Á                  ;zerï extent
	LÄ   (CCP$FCB+15),A
	LÄ   HL,°               ;starô aô beginninç oæ file
	LÄ   (FCB$NR),HL
     	LÄ   DE,CCP$FCB		;opeî filå containinç CCP
        CALÌ OPEN
	INÃ  Á                  ;erroò iæ nï filå ...
	JÒ   Z,NO$CCP
	LÄ   DE,0100È 		;starô oæ TPA
	CALÌ SETDMA
	LÄ   DE,12¸  		;allo÷ uğ tï 16ë bytes
	CALÌ SETMULTI
	LÄ   DE,CCP$FCB		;loaä thå thing
	CALÌ READ		;now¬ copù CCĞ tï secreô banë foò reloading

;movå copù oæ CCĞ intï secreô bank:
	LÄ   HL,0100H		;sourcå      addresó --¾ reg® HL
	LÄ   DE,3500H		;destinatioî addresó --¾ reg® DE
     	LÄ   B,25		;recorä counô        --¾ reg® B
LDLOOPº PUSÈ BC			;savå recorä count
	LÄ   A,10H		;sourcå      banë ½ 1
        			;destinatioî banë ½ 0
	LÄ   BC,12¸ SHÌ 8+15	;bytå counô --¾ reg® B
	          		;function £ --¾ reg® C
	CALÌ ?USERF		;movå CCĞ record
	LÄ   BC,128		;recorä lengtè --¾ reg® BC
	ADÄ  HL,BC		;bumğ sourcå address
	EØ   DE,HL
	ADÄ  HL,BC		;bumğ destinatioî address
	EØ   DE,HL
	POĞ  BC			;restorå recorä count
	DJNÚ LDLOOP		;movå nexô record	
	RET			;returî tï caller
	
;herå iæ wå couldn'ô finä thå file:
NO$CCP:	LÄ   HL,CCP$MSG		;reporô thió ...
	CALÌ ?PMSG
	CALÌ ?CONIN		;geô response
	JÒ   ?LDCCP		;anä trù again

;reloaä CCP:
?RLCCP:	LÄ   HL,3500H		;sourcå      addresó --¾ reg® HL
	LÄ   DE,0100H		;destinatioî addresó --¾ reg® DE
     	LÄ   B,25		;recorä counô        --¾ reg® B
RLLOOPº PUSÈ BC			;savå recorä count
	LÄ   A,01H		;sourcå      banë ½ 0
        			;destinatioî banë ½ 1
	LÄ   BC,12¸ SHÌ 8+15	;bytå counô --¾ reg® B
	          		;functioî £ --¾ reg® C
	CALÌ ?USERF		;movå CCĞ record
	LÄ   BC,128		;recorä lengtè --¾ reg® BC
	ADÄ  HL,BC		;bumğ sourcå address
	EØ   DE,HL
	ADÄ  HL,BC		;bumğ destinatioî address
	EØ   DE,HL
	POĞ  BC			;restorå recorä count
	DJNÚ RLLOOP		;movå nexô record	
	RET			;returî tï caller
	

*EJECT
;Externaì clock.
?TIME:	PUSÈ HL			;savå reg® HÌ ¦ DE
	PUSÈ DE
        INÃ  Ã  		;timå get/seô flaç ?
	JÒ   Z,SET$TIM		;seô time
	LÄ   HL,@DATE		;^(timå ¦ datå buffer© --¾ reg® HL
	LÄ   C,18		;functioî £ 	       --¾ reg® C
	JÒ   GET$TIM		;geô timå ¦ datå anä returî tï caller
SET$TIM:LÄ   HL,(@DATE)		;date		       --¾ reg® HL
	LÄ   A,(@HOUR)		;hours		       --¾ reg® D
	LÄ   D,A
	LÄ   A,(@MIN)		;minutes	       --¾ reg® E
	LÄ   E,A
	LÄ   C,1¹ 		;functioî #	       --¾ reg® C
GET$TIM:CALÌ ?USERF		;seô timå ¦ datå anä returî tï caller
	POĞ  DE			;restorå reg® HÌ ¦ DE
	POĞ  HL
	RET


;CP/Í BDOÓ functioî interfaces
OPEN:	LÄ   C,15		;opeî filå controì block
	JĞ   BDOS
SETDMA:	LÄ   C,26		;seô datá transfeò address
	JĞ   BDOS
SETMULTI:
	LÄ   C,44		;seô recorä count
	JĞ   BDOS
READ:	LÄ   C,20		;reaä records
	JĞ   BDOS
	

*EJECT
SIGNON$MSG:
        DEFÂ CR,LF,LF,LF,LF,LF,LF,LF,LF,RS,ESC,'R'
	DEFÍ § Ã Ğ ¯ Í   Ö å ò ó é ï î   ³ '
	DEFÂ ESC,'S',CR,LF,LF
	DEFÍ 'GENIÅ IIIó SYSTEM'
	DEFÂ CR,LF
	DEFÍ 'Versioî â oæ BIOÓ (851120)'
	DEFÂ CR,LF
	DEFÍ 'Thomaó Holtå '
	DEFÂ 98H
	DEFÍ § 1985'
        DEFÍ § letztå [nderunç F.Chwolká 07/05/199² § 
	DEFÂ CR,LF,LF,LF,LF,LF,LF,LF,LF,LF,LF,LF,0
ENDMSG	EQÕ  $

CCP$MSG:DEFÂ CR,LF,CR,LF
	DEFÍ 'BIOÓ Erò oî Aº Nï CCP.COÍ file'
	DEFÂ 0

CCP$FCB:DEFÂ 1
	DEFÍ 'CCP     COM'
	REPÔ 20
	DEFÂ 0
	ENDM

FCB$NR:	DEFÂ 0,0,0

	END
