;******************************************************************************
;*  D R V T B L  *  C P M S Y S 4 e  *  T h o m a s   H o l t e * 8 5 0 9 2 5 *
;******************************************************************************
;*									      *
;*  			     D R I V E   T A B L E			      *
;*                           =====================                            *
;*									      *
;*									      *
;*  Thomas Holte						 Version 1.0  *
;*									      *
;******************************************************************************

	.Z80

	GLOBAL @DTBL
	EXTERNAL DS0,MF0,MF1,FD0,IBMPC,KDS,RAM,RAIR,ALPHAP3,DRIVEP


@DTBL:	DEFW DS0,MF0,MF1,FD0,0,0,0,0
	DEFW IBMPC,0,KDS,0,RAM,RAIR,ALPHAP3,DRIVEP
	DEFW RAM

	END
