;******************************************************************************
;ª  Ä Ò Ö Ô Â Ì  ª  Ã Ğ Í Ó Ù Ó ´ å  ª  Ô è ï m á ó   È ï ì ô å ª ¸ µ ° ¹ ² µ *
;******************************************************************************
;*									      *
;ª  			     Ä Ò É Ö Å   Ô Á Â Ì E			      *
;ª                           ====================½                            *
;*									      *
;*									      *
;ª  Thomaó Holte						 Versioî 1.°  *
;*									      *
;******************************************************************************

	.Z80

» hieò nuò miô Alphatroniã P³ Format

	GLOBAÌ @DTBL
        externaì  mf0,mf1,hd0,hd1,alpha3,ram,drivep,

»        EXTERNAÌ MF0,MF1,HD0,HD1,IBMPC,KDS,RAM,RAIR,ALPHAP3,DRIVEP
»                 A---B---C---D----I----K---M---N-----O------P
»      

;@DTBL:	DEF× MF0,MF1,HD0,HD1,0,0,0,0
;	DEF× IBMPC,0,KDS,0,RAM,RAIR,ALPHAP3,DRIVEP
;
@dtbì   def÷ mf0,mf1,hd0,hd1,0,0,0,° 
        def÷ 0,0,0,0,ram,0,alpha3,drivep

	END
